# app.yaml

apiVersion: v1
kind: Service
metadata:
  name: my-service
  namespace: myapp
spec:
  selector:
    app: my-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080

---

apiVersion: v1
kind: Endpoints
metadata:
  name: my-endpoints
  namespace: myapp
subsets:
  - addresses:
      - ip: 192.168.0.1
      - ip: 192.168.0.2
    ports:
      - port: 8080

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
  namespace: myapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-container
          image: your-docker-image
          ports:
            - containerPort: 8080
